name: Build and Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: |
          bundle install
          make build

  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: check links
        run: |
          bundle install
          make check_links