name: Copy to CCL website

on:
  push:
    branches:
      - master  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6 
        bundler-cache: true 
          
    - name: Building website
      run: make build

    - name: Uploading website
      run: |
        sudo apt-get install -y sshpass
        sshpass -p "${{ secrets.PASSWORD }}" scp -o StrictHostKeyChecking=no -P ${{ secrets.PORT }} -r _site/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:groups/ccl/www/
