name: Copy to CCL website

on:
  push:
    branches:
      - master  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Building website
      run: |
        sudo apt-get install -y ruby-full build-essential zlib1g-dev
        sudo gem install bundler
        bundle update
        make build

    - name: Uploading website
      run: |
        sudo apt install sshpass
        sshpass -p "${{ secrets.PASSWORD }}" scp -o StrictHostKeyChecking=no -P ${{ secrets.PORT }} -r _site/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:groups/ccl/www/
